
server:
  port: 0

spring:
  application:
    name: pay-service
  datasource:
    url: jdbc:mysql://localhost:3306/pay?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.184:8761/eureka

  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
